### ISSUE TITLE
capture parent url of embed, capture in analytics

### ISSUE THREAD

**Issue by eads** [nprapps/dailygraphics#115]
From Dan Frolich:

<blockquote>
<p>We track two main things, both as session level custom dimensions, the full URL where the story is embedded and the hostname of where the story is embed.</p>
 
<p>So, for example, if something gets embedded on this page: www.myblog.com/the-specific-page</p>
 
<p>The first (full url) custom dimension will capture: www.myblog.com/the-specific-page<br/>
The second (hostname) custom dimension will capture: www.myblog.com</p>
</blockquote>

**Comment by onyxfish** [comment]
We're already grabbing these two.

**Comment by eads** [comment]
Just as a follow-up, do we want to follow the way the analytics team is doing it? I know @brianboyer was interested in that, but I don't know if there's compelling reason as long as we can still do apples-to-apples comparisons to .org if we need.

**Comment by onyxfish** [comment]
Pretty sure we're doing it the same way. The idea came out of my earlier conversation with Dan.

**Comment by eads** [comment]
Awesome!

On Fri, May 22, 2015 at 10:04 AM, Christopher Groskopf <
notifications@github.com> wrote:

> Pretty sure we're doing it the same way. The idea came out of my earlier
> conversation with Dan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nprapps/dailygraphics/issues/115#issuecomment-104668245>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
