### ISSUE TITLE
Line chart Google doc appears to be protected

### ISSUE THREAD

**Issue by brentajones** [nprapps/dailygraphics#123]
I created a new line chart, then visited it (after running fab app) on my local machine. This throws an error: KeyError: 'Error! Google returned a 403 error'

The command line when creating the chart also shows an error:

```
Creating spreadsheet...
Error creating spreadsheet (status code 404) with message Not Found
```

Pasting the graphic_config key into a google docs URL tells me to ask permission to see the document.

**Comment by onyxfish** [comment]
Good catch. Can you try now and let me know if it's fixed?

**Comment by brentajones** [comment]
Looks good now. Thanks for the quick fix!
