### ISSUE TITLE
New analytic thing: time lingered

### ISSUE THREAD

**Issue by brianboyer** [nprapps/dailygraphics#124]
Can we know:

1) how many people even saw the graphic?
2) how long people spent looking at it?

We'd note if it entered the viewport, and then periodically note how long it has been in the viewport?

**Comment by alykat** [comment]
Related to #114

**Comment by alykat** [comment]
We have this with Carebot. Should we close this task (rather than build a dailygraphics-specific version)?

**Comment by eads** [comment]
Definitely should close.
