### ISSUE TITLE
Custom Jinja filters?

### ISSUE THREAD

**Issue by brentajones** [nprapps/dailygraphics#131]
Hi Visuals Team!

I used to be able to write my own custom Jinja filters in render_utils.py, then import them into app.py. That doesn't seem to be working anymore (I'm guessing it has to do with graphics.py?).

I looked at your code and can't find any filters in use — there are a couple still defined in render_utils, but I couldn't find them referenced anywhere else in the app in a GitHub search.

I tried adding my filters into graphics.py, but the app still said the filter didn't exist. Is this still possible to do, and if it isn't too much trouble, would someone mind pointing out how?

Thanks.

**Comment by onyxfish** [comment]
Yeah, I've also run into a need for this. As it stands now I don't believe it's possible, but I'd like to bring support for this back--maybe even on a per-graphic basis. I'll need to look into the best way to support it.

**Comment by eads** [comment]
Do you hear that? It's ol' Ida Tarbell, whispering in your ear...

Even if Tarbell isn't right for Daily Graphics, the way it loads projects
could be pretty instructive for this purpose. The Tarbell blueprint is also
a Flask blueprint, as are Tarbell projects, so the project blueprint *and*
project can define custom routes, filters, etc.

On Fri, Jul 10, 2015 at 9:01 AM, Christopher Groskopf <
notifications@github.com> wrote:

> Yeah, I've also run into a need for this. As it stands now I don't believe
> it's possible, but I'd like to bring support for this back--maybe even on a
> per-graphic basis. I'll need to look into the best way to support it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nprapps/dailygraphics/issues/131#issuecomment-120404934>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
