### ISSUE TITLE
issue matrix google spreadsheet template is private

### ISSUE THREAD

**Issue by brentajones** [nprapps/dailygraphics#154]
Hi! I think the Google Doc (key: 18g7ExcIMXcSpVGMcQYAIHvmGqMzf9j15woW8UmsgmGU) for the template for the issue matrix is private.

When I run `fab add_issue_matrix:[slug]`, I get:

```
Creating spreadsheet...
Error creating spreadsheet (status code 404) with message Not Found
```

Thanks!

**Comment by alykat** [comment]
Try now?

**Comment by brentajones** [comment]
Perfect! Thanks for getting to it so quickly.
