### ISSUE TITLE
Adding additional jinja filters requires restart of local webserver

### ISSUE THREAD

**Issue by katiepark** [nprapps/dailygraphics#160]
For example: https://github.com/nprapps/graphics/blob/master/schools-whose-job-20160108/base_filters.py

I added some filters to base_filters.py and included them in the `FILTERS` list at the end. Loading the graphic's preview page returns `TemplateAssertionError: no filter named 'split_list'`. If you stop and restart fab, the graphic loads the filter without error.

**Comment by alykat** [comment]
I've noticed that sometimes even editing one of the existing filters (say, adding additional states to postal->AP converter, as I did with the [primary calendar](https://github.com/nprapps/graphics/blob/master/table-primary-calendar-20160125/base_filters.py)) will occasionally result in a similar error that's remedied by restarting the local webserver.
