### ISSUE TITLE
Assets rig doesn't always sync

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#180]
I've noticed I have to explicitly run `assets.sync:$slug` to get the assets rig to sync. Doesn't happen with publish like it used to.

**Comment by katiepark** [comment]
I have a hunch for why this might happen, though I haven't tested it extensively.

When publishing out an animated filmstrip, I have a folder of images (non-public-facing) with capital letters in the name. This seems to publish out to the production s3 path, but it raises an error when syncing the assets bucket:

    The following filenames are not lowercase, please change them before running `assets.sync`

This appears to stop the `assets.sync` process before it syncs the other files.

Not conclusive or comprehensive, but it might explain the inconsistent behavior we're seeing with assets not syncing at deploy time?

**Comment by jjelosua** [comment]
@alykat would it be possible that the `USE_ASSETS` was set to `false`? That would not sync assets but will push it to the public facing graphic bucket on S3....

**Comment by alykat** [comment]
@jjelosua I suspect that what @katiepark suggested is the most likely explanation: That the uppercase constraint meant that assets syncing was failing, but I never saw the error because everything else published successfully. What you've done in https://github.com/nprapps/dailygraphics/commit/311a0db416ffdf802564325d21571ae5821d5f3a should address this.

**Comment by jjelosua** [comment]
@alykat Should we close this then?
