### ISSUE TITLE
When creating a new graphic, the user sometimes gets the template doc rather than a new doc

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#185]
Noted recently by @Kurtzleben

**Comment by Kurtzleben** [comment]
Also today, creating a new table, it linked me to the spreadsheet for a chart I made yesterday.

**Comment by alykat** [comment]
@TylerFisher addressed part of this in 47659c22e9aaa9f60bc4b33d0a502811c99df5fa. Not sure what would account for the odd case where Danielle saw the spreadsheet from a past graphic pop up. Haven't seen this recur since that fix. Closing for now, but will reopen if it comes up again.
