### ISSUE TITLE
clone_graphic: Handle clones made on the same day

### ISSUE THREAD

**Issue by katiepark** [nprapps/dailygraphics#187]
`fab clone_graphic`, unless passed a new destination slug, currently duplicates the cloned slug and updates the date. If this command is run on the same day that the original graphic was made, the error message is `Error: Directory already exists`.

This is pretty trivial since a new destination slug can easily be specified, but it might help to make the error language more specific.

**Comment by jjelosua** [comment]
Fixed in c10d765
