### ISSUE TITLE
Adjust all Headers to be secure when republishing 

### ISSUE THREAD

**Issue by esomo22e** [nprapps/dailygraphics#210]

**Comment by eads** [comment]
@esomo22e can you access this? http://confluence.npr.org/display/TECH/HTTPS+Headers+Progress

That's the internal wiki page on the headers we need and progress towards getting them implemented.

**Comment by jjelosua** [comment]
This should be handled using lambda@edge will focus on that in the beginning of next week, if I am correct and we do it on `origin response` we would have to wait for the cache to expire to see the headers or invalidate cloudfront...I would argue for waiting for that to happen as objects expire... @eads do these headers have a deadline or can we wait to the objects to expire?

**Comment by jjelosua** [comment]
We have added `x-content-type-options` and `x-xss-protection` to `apps.npr.org`.

**Comment by alykat** [comment]
Safe to say this is done?
