### ISSUE TITLE
Interested in a PR for a leaflet map?

### ISSUE THREAD

**Issue by brentajones** [nprapps/dailygraphics#217]
Hi NPR friends. Would you all be interested in a pull request for a template adding a leaflet map? If so, I'm interested in working on this to increase my github skills.

Here's my template: https://github.com/stlpublicradio/dailygraphics/tree/master/graphic_templates/map

And here are a couple examples in one story of my using the template: http://news.stlpublicradio.org/post/st-louis-takes-new-look-old-problem-what-do-vacant-land-and-abandoned-buildings#stream/0

**Comment by alykat** [comment]
Cool! Will take a look this week.

**Comment by brentajones** [comment]
I had another thought about this: If it doesn't make sense to include with the "core" set of dailygraphics templates, I wonder if we could have a repo where anyone could contribute templates and folks could choose whatever they needed, like plugins or modules.

**Comment by chagan** [comment]
Brent and I were chatting about this, and as a user I would be open to the plugin idea if there was worry about adding too many templates to the core repo.
