### ISSUE TITLE
Missing Yaml File in Locator Map Template

### ISSUE THREAD

**Issue by LeanneAbraham** [nprapps/dailygraphics#233]
When you run fab add_map the locator map isn't always created with a yaml file.

**Comment by katiepark** [comment]
This works properly for me, but when @LeanneAbraham creates a new map, the yaml file is not created. She's on master and pulled the latest changes. Might be something specific to her computer, but figured I should log it here for reference.

**Comment by alykat** [comment]
Can't replicate, and [the yaml file is in the templates folder](https://github.com/nprapps/dailygraphics/blob/master/graphic_templates/locator_map/geodata.yaml). Going to close this. Can reopen if we see it again.
