### ISSUE TITLE
Auto-generate dates for new graphics

### ISSUE THREAD

**Issue by katiepark** [nprapps/dailygraphics#237]
Automatically append a date to the slug when creating a graphic, similar to the way `fab clone_graphic` does it: https://github.com/nprapps/dailygraphics/blob/8206f884ba5e77e15124a1bf5304020e7683ad92/fabfile/__init__.py#L233

**Comment by jjelosua** [comment]
@katiepark How would you want that to happen? If it has a date leave it and if it does not then add today's date?

**Comment by katiepark** [comment]
I think that makes sense.
