### ISSUE TITLE
Fix wrapText assignment of dy attribute

### ISSUE THREAD

**Issue by katiepark** [nprapps/dailygraphics#247]
A one-line fix. The `wrapText` helper function needs to include the initial `dy` value in addition to any line height offset. It also needs to specify the unit of the value -- can be hard coded to pixels until #248 (handling of units) is closed.

**Comment by ghing** [comment]
Is this something that works sometimes, or that you have to fix each time you use it?

**Comment by katiepark** [comment]
It works fine if there's no dy value initially set. I'm just about to push a fix to this that should work in either scenario, though...
