### ISSUE TITLE
Conditionally include D3/Underscore for rig graphics that need them

### ISSUE THREAD

**Issue by petulla** [nprapps/dailygraphics#261]
Hi there

I don't have much experience with Fab, so hoping someone can help.

As it is, D3 and underscore are included in the `base_template` of every graphic, like this:

```
{% block js %}
        {{ JS.push('js/lib/underscore.js') }}
        {{ JS.push('js/lib/d3.min.js') }}
        {{ JS.push('js/lib/modernizr.svg.min.js') }}
        {{ JS.push('js/base.js') }}
        {{ JS.push('js/graphic.js') }}
        {{ JS.render('js/graphic-footer.js') }}
    {% endblock js %}
```

The issue is not all graphics need d3 or underscore. For example, ai2html shouldn't require either. If more than one rig page, the libraries are included for every graphic.

I'm looking to see if there is a way to detect what kind of graphic is being created and include JS libraries accordingly.

Something like this. It's not clear to me how the graphic type parameter could be passed to `base_template.html`

```

{% block js %}
  {{ JS.push('js/lib/modernizr.svg.min.js') }}
{% if GRAPHIC_TYPE not in ('AI2html','table','etc') %}
  {{ JS.push('js/lib/d3.min.js') }}
  {{ JS.push('js/lib/underscore.js') }}
 {% endif %}
  {{ JS.push('js/base.js') }}
  {{ JS.push('js/graphic.js') }}
  {{ JS.render('js/graphic-footer.js') }}
{% endblock js %}

```

**Comment by alykat** [comment]
You can override blocks of code in `base_template.html` in each graphic's `child_template.html` file. For example, the ai2html template is set up to only include `graphic.js`: https://github.com/nprapps/dailygraphics/blob/master/graphic_templates/ai2html_graphic/child_template.html#L26-L29

More in the Jinja template docs: http://jinja.pocoo.org/docs/2.10/templates/#template-inheritance

**Comment by petulla** [comment]
Thanks, @alykat.
