### ISSUE TITLE
Improve SVG accessibility

### ISSUE THREAD

**Issue by petulla** [nprapps/dailygraphics#276]
@alykat 

Hey Alyson,

I just took a pretty hard pass on CNN's rig to improve screen reader and assisted device SVG accessibility. I'm still working on it and need to do more testing with Windows screen readers but it makes improvements on the current templates.

Are you interested in a PR with my changes? .

**Comment by alykat** [comment]
Oh cool! Thank you for offering! I'd love to see what you've done.

**Comment by petulla** [comment]
@alykat Hey, just an update on this. We're trying to os the CNN dailygraphics rig, which migrates the project to Node (and has these updates). Hope to have some news in the coming months but wanted to close the loop on why I didn't submit these changes.

**Comment by thomaswilburn** [comment]
Thanks, Sam! I'm going to be working on accessibility and the daily graphics templates as one of my initial tasks, so I'd love to have any info that came up during your work on it.

**Comment by petulla** [comment]
Cool, @thomaswilburn. This was my framework for accessibility:

Follow [this guide](https://css-tricks.com/accessible-svgs/) and [this guide](https://www.w3.org/TR/wai-aria-practices-1.1/examples/table/table.html).

-Add HTML5 semantic markup to all child pages
-Add title/desc to all SVGs
-Add aria roles and alt titles to chart elements
-Add ARIA information to tables
-Add title to graphics iframe

In some cases, accessibility is aspirational and not supported yet by current browsers. Still, having these improvements in place for when browsers have better SVG accessibility support seemed worthwhile.

Ill drop you an email so we can chat more off the issues thread.

**Comment by petulla** [comment]
Closing in favor of this [PR](https://github.com/nprapps/dailygraphics/pull/300)
