### ISSUE TITLE
Responsive table not working in IE9?

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#37]
Running into issues with this table:
http://www.npr.org/templates/story/story.php?storyId=297331252&live=1
(slugged table-televangelists in the repo: https://github.com/nprapps/dailygraphics/tree/master/www/graphics/table-televangelists )

Works fine in my IE9 emulator. But Alicia and Ashley report that when they pull it up in IE9 (compatibility mode on by default), nothing shows up. Alicia found that if she disables compatibility mode, the first few lines of the table show up (the default iframe height before resizing?), but nothing else.

**Comment by onyxfish** [comment]
No more IE9 for us!
