### ISSUE TITLE
Pass in the name of a sheet, output a json object

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#53]
Use case: Keep my (simple) dataset and my copy/labels in the same Google Spreadsheet, and avoid having to separately load/maintain a CSV. I would, in theory, pass the name of a sheet into a template tag, and it would output a JSON object with the data.

Crazy idea?

**Comment by onyxfish** [comment]
Done! @dannydb your solution was great, I just made a few minor tweaks to reduce code duplication.
