### ISSUE TITLE
Google ClientLogin deprecated

### ISSUE THREAD

**Issue by vienno** [nprapps/dailygraphics#66]
I can't seem to run `fab add_graphic:mygraphic` because of a failed authentication attempt with Google. 

    File "[...]/etc/gdocs.py", line 70, in get_auth
    self.auth = r.content.split('\n')[2].split('Auth=')[1]
    IndexError: list index out of range

I tried making the same post request manually and got a 403 forbidden response with the header message "BadAuthentication". Indeed, the [ClientLogin API seems to have been deprecated](http://googledevelopers.blogspot.se/2012/04/changes-to-deprecation-policies-and-api.html) a while back..

**Comment by alykat** [comment]
Hello! Apologies for the delayed response. Yes, syncing with Google didn't work if you were using a Google account that had two-factor authentication enabled. We've just rolled in support for OAuth authentication instead.
