### ISSUE TITLE
Assets uploaded via another machine aren't syncing

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#67]
I've noticed that ```fab assets.sync:SLUG``` doesn't seem to be pulling images off the remote server.

Example: ```nola-transportation```, which I built with my old computer. The map images are on the live server, but when I run ```fab assets.sync:nola-transportation```, none of them download locally. I only see a prompt to upload ```assetsignore```.

```
(dailygraphics)ahurt-npr:dailygraphics AHurt$ fab assets.sync:nola-transportation
/Users/AHurt/src/graphics/nola-transportation/assets/assetsignore
--> This file does not exist on S3.
Upload local copy [u] Delete local copy [d] Upload all [ua] Delete all [da] cancel [c] u
--> Uploading!

Done.
```

**Comment by onyxfish** [comment]
Double-check that assets are synced on publish.

**Comment by onyxfish** [comment]
Made assets sync on deploy. Provisionally fixed.
