### ISSUE TITLE
Serialized JSON brings columns in reverse order

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#72]
Order in the JSON object:

![image](https://cloud.githubusercontent.com/assets/491318/5903634/e31880fc-a550-11e4-90d8-3dc7bd03cf63.png)

And thus on the chart:

![image](https://cloud.githubusercontent.com/assets/491318/5903600/b3895780-a550-11e4-9195-cde0655c8b2c.png)

Would be ideal if they displayed in the same order as they appear in the spreadsheet:

![image](https://cloud.githubusercontent.com/assets/491318/5903614/c2869e64-a550-11e4-9c7f-b9997988ceb2.png)

https://docs.google.com/spreadsheets/d/18HIRf1ZSWbK1od50DiwBbsiBlrp63DuEt4nIImWU5zA/edit#gid=23386656

Test graphic:
https://github.com/nprapps/graphics/tree/master/test-json-object-line

**Comment by onyxfish** [comment]
Fixed
