### ISSUE TITLE
Default graphic: U.S. state cartogram(s)

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#79]

**Comment by alykat** [comment]
Quick thoughts:
- Need to be able to scale / have multiple instances in the same graphic (say, small multiples of cartograms)
- Optional state labels (postal abbr)
- Need to be able to loop through / address each state block
- Pass data in via a Google Spreadsheet (using state postal abbr as the key?)
- Handle color bins somehow. I imagine in most cases we'll be doing some kind of binary: does the state meet a certain criteria — Y/N. But sometimes we might want to do a color ramp instead. I have some examples of how I've done this in the past in D3 maps.

**Comment by onyxfish** [comment]
We've got one!
