### ISSUE TITLE
Cache headers on assets

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#81]
Check the cache expiration for things uploaded via the assets rig. Ran into a problem during the Wal-Mart maps project where updated images didn't seem to be refreshing (or, at least, refreshing quickly enough).

**Comment by onyxfish** [comment]
We might want to revisit how this works for dailygraphics. It's generally a pretty different use-case than app-template projects. Let's discuss.

**Comment by onyxfish** [comment]
Add timeout override to `graphic_config.py`
