### ISSUE TITLE
Should we have different boilerplate spreadsheets for each chart type?

### ISSUE THREAD

**Issue by onyxfish** [nprapps/dailygraphics#94]
If so we could move the data from `data.csv` into the spreadsheet without cluttering things up

**Comment by alykat** [comment]
Yeah, probably. However, @qdinhbui2 has expressed a preference for NOT moving the data into the spreadsheet — he'd prefer to swap out CSVs. So we'd need to figure out an easy way to manage both use cases.

**Comment by onyxfish** [comment]
Okay that's fair. Not totally straight-forward to support both but I bet we can figure something out.
